apiVersion: skaffold/v2beta3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # Can only be local or googleCloudBuild
#  local:
#    push: false
  googleCloudBuild:
    projectId: marc-ticketing-dev
  artifacts:
#    - image: mschregardus/auth
    - image: us.gcr.io/marc-ticketing-dev/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
