apiVersion: skaffold/v2beta3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # Can only be local or googleCloudBuild
  local:
    push: false
#  googleCloudBuild:
#    projectId: marc-ticketing-dev
  artifacts:
#    - image: us.gcr.io/marc-ticketing-dev/auth
    - image: mschregardus/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: mschregardus/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: mschregardus/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: mschregardus/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
